### ISSUE TITLE
Upload standard in workable format

### ISSUE THREAD

**Issue by peterdesmet** [inbo/ctms#3]
We should upload CTMS in a workable format. Options:

- CSV: machine-readable, but a bit cumbersome to edit online

```
Field Name,Part of,Description,Valid Values,Default Value,Format,Darwin Core
projectID,,Unique identifier for the project,Numeric or alphanumeric,NA,url or text,datasetID
projectName,,Name of the project.,NA,NA,text,collectionCode or datasetName
```

- Tables in Markdown: easy to consume as humans, not very machine readable

Field Name | Part of | Description | Valid Values | Default Value | Format | Darwin Core
--- | --- | --- | --- | --- | --- | ---
projectID |  | Unique identifier for the project | Numeric or alphanumeric | NA | url or text | datasetID
projectName |  | Name of the project. | NA | NA | text | collectionCode or datasetName

- YAML: human and machine readable, but have to repeat field names

```YAML
-  projectID:
    partOf:
    description: Unique identifier for the project
    validValues: Numeric or alphanumeric
    defaultValue:
    format: url or text
    darwinCore: datasetID
-  projectName:
    partOf:
    description: Name of the project
    validValues: 
    defaultValue: 
    format: url or text
    darwinCore: datasetName
```

**Comment by jimcasaer** [comment]
my preference are the Markdowns :-)

**Comment by milotictanja** [comment]
I'd go for Markdown too (or maybe YAML) because it is readable and can be adapted easily online by anyone

**Comment by peterdesmet** [comment]
Ok, instead of markdown tables (which need to be scrolled left/right), I'll go for a combination of Markdown **headers** (which allows them to have an anchor link), text for the definition, and yaml for properties. This also allows for easier comparison in pull requests (lines are better than columns):

### projectDesign

Description of study design that includes at a minimum:

- Method for selecting camera points (random, stratified, targeted, etc.)
- Paired Cameras (Y/N)
- Spacing of cameras (m)
- Any grouping or clustering of points

```yaml
valid_values: NA
default_value: NA
format: text
fgdc: "Identification information: abstract or purpose"
dwc: "Event: samplingprotocol"
eml_module: EML Methods
ac: http://terms.tdwg.org/wiki/Audubon_Core_Term_List#dcterms:description
```
